<?php
/**
 * Generated configuration file
 * Generated by: phpMyAdmin 5.2.0 setup script
 * Date: Tue, 26 Jul 2022 08:52:24 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '8000';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
// $cfg['Servers'][$i]['user'] = 'r';
// $cfg['Servers'][$i]['AllowPassword'] = TRUE;
// $cfg['Servers'][$i]['Password'] = "1234";

/* End of servers configuration */

$cfg['blowfish_secret'] = 'FK`aU,j&E?G3V)CX,:@R?(%\\"Ak+(ohh';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';

/* User for advanced features */
$cfg['Servers'][$i]['controluser'] = 'khoji'; 
$cfg['Servers'][$i]['controlpass'] = '1234';

// https://stackoverflow.com/questions/46736319/phpmyadmin-error-mysqli-real-connect-hy000-1045-access-denied-for-user-p
